# _config.yml

title: BC Cash Flow
description: Documentação oficial do BC Cash Flow
url: "https://mfedatto.github.io/bc-cashflow"

theme: "just-the-docs"

just_the_docs:
  search_enabled: true
  nav_to_top: true

author:
  name: "Seu Nome"
  email: "seuemail@exemplo.com"

layout: "default"

include:
  - docs

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - _config.yml

social:
  twitter: "mfedatto"
  github: "mfedatto"

permalinks:
  pretty: true

show_errors: true
