# _config.yml

title: BC Cash Flow
description: Documentação oficial do BC Cash Flow
url: "https://mfedatto.github.io/bc-cashflow"

author:
  name: "Maurício Fedatto"
  email: "mfedatto@gmail.com"

layout: "default"

include:
  - docs

plugins:
  - jekyll-feed
  - jekyll-seo-tag

social:
  twitter: "mfedatto"
  github: "mfedatto"

permalinks:
  pretty: true

show_errors: true
