# _config.yml

remote_theme: jekyll-theme-hacker
plugins:
- jekyll-remote-theme

title: BC Cash Flow
description: Documentação oficial do BC Cash Flow
url: "https://mfedatto.github.io/bc-cashflow"

author:
  name: "Maurício Fedatto"
  email: "mfedatto@gmail.com"

show_downloads: false

social:
  github: "mfedatto"

permalinks:
  pretty: true

show_errors: true