# _config.yml

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: BC Cash Flow
description: Documentação oficial do BC Cash Flow
url: "https://mfedatto.github.io/bc-cashflow"

author:
  name: "Maurício Fedatto"
  email: "mfedatto@gmail.com"

layout: "default"

include:
  - docs

show_downloads: false

social:
  github: "mfedatto"

permalinks:
  pretty: true

show_errors: true