@startuml

!include defaults.plantuml

left to right direction

actor "User" as user
actor "Admin" as admin

usecase "Registrar Lançamento de Crédito" as UC1
usecase "Registrar Lançamento de Débito" as UC2
usecase "Consultar Saldo Atual da Conta" as UC3
usecase "Gerar Relatório Diário" as UC4
usecase "Visualizar Histórico de Transações" as UC5
usecase "Atualizar Tipo de Conta" as UC6
usecase "Configurar Tarifas e Prazos" as UC7
usecase "Criar Nova Conta" as UC8
usecase "Consultar Previsão de Pagamento" as UC9

user --> UC1
user --> UC2
user --> UC3
user --> UC4
user --> UC5
user --> UC9

admin --> UC6
admin --> UC7
admin --> UC8

@enduml
