services:

  cashflow-db:
    extends:
      file: docker-compose.bccf.yaml
      service: _service
    image: mcr.microsoft.com/mssql/server:latest
    container_name: cashflow-db
    hostname: cashflow-db
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: $CASHFLOW_DB_SU_PWD
      MSSQL_PID: $MSSQL_PID
    volumes:
      - cashflow-db:/var/opt/mssql
    ports:
      - 1433:1433
    networks:
      cashflow-db:

  cashflow-db-create-database:
    extends:
      file: docker-compose.db-migration.yaml
      service: _db-migration
    container_name: cashflow-db-create-database
    hostname: cashflow-db-create-database
    environment:
      CONNECTION_STRING: Server=cashflow-db;Database=master;UID=sa;PWD=${CASHFLOW_DB_SU_PWD}
      LOCATIONS: /migrations
    volumes:
      - ./cashflow-db-create-database:/migrations
    networks:
      cashflow-db:
    depends_on:
      - cashflow-db

  cashflow-db-create-user:
    extends:
      file: docker-compose.db-migration.yaml
      service: _db-migration
    container_name: cashflow-db-create-user
    hostname: cashflow-db-create-user
    environment:
      CONNECTION_STRING: Server=cashflow-db;Database=BCCF;UID=sa;PWD=${CASHFLOW_DB_SU_PWD}
      LOCATIONS: /migrations
      PLACEHOLDERS: bccf_db_username:${CASHFLOW_DB_USERNAME};bccf_db_password:${CASHFLOW_DB_PASSWORD}
    volumes:
      - ./cashflow-db-create-user:/migrations
    networks:
      cashflow-db:
    depends_on:
      - cashflow-db
      - cashflow-db-create-database

  cashflow-db-migration:
    extends:
      file: docker-compose.db-migration.yaml
      service: _db-migration
    container_name: cashflow-db-migration
    hostname: cashflow-db-migration
    environment:
      CONNECTION_STRING: Server=cashflow-db;Database=${CASHFLOW_DB_USERNAME};UID=sa;PWD=${CASHFLOW_DB_PASSWORD}
      LOCATIONS: /migrations
    volumes:
      - ../db/migrations:/migrations
    networks:
      cashflow-db:
    depends_on:
      - cashflow-db
      - cashflow-db-create-database
      - cashflow-db-create-user

networks:
  cashflow-db:
    driver: bridge

volumes:
  cashflow-db:
